Import necessary libraries

In [90]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Read data

In [91]:
metadata = pd.read_csv("../../data/raw/metadata_raw.csv")
responses = pd.read_csv("../../data/raw/counterfactual_responses_raw.csv")

Responses dataset:

Cleaning leading or trailing whitespaces in "Response"

In [92]:
responses["Response"] = responses["Response"].str.strip()
responses["Response"].value_counts(dropna= False)

Response
L1_transfer    149
correct        104
L2_other        72
NaN             11
Name: count, dtype: int64

In [93]:
responses["Response"].shape

(336,)

Rename "Participant_ID"

In [94]:
responses = responses.rename(
    columns={"Partcipant_ID": "Participant_ID"}
)

Include Null values in "Response" as category

In [95]:
responses["Response_Full"] = (
    responses["Response"]
    .fillna("null")
)

In [96]:
responses["Response_Full"].value_counts()

Response_Full
L1_transfer    149
correct        104
L2_other        72
null            11
Name: count, dtype: int64

Responses dataset validation

In [97]:
responses.shape

(336, 10)

In [98]:
responses.columns

Index(['Participant_ID', 'Focus', 'Agent', 'Goal_Type', 'Item', 'Item_string',
       'Item_len', 'Response_tag', 'Response', 'Response_Full'],
      dtype='str')

In [99]:
responses.info()

<class 'pandas.DataFrame'>
RangeIndex: 336 entries, 0 to 335
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Participant_ID  336 non-null    str
 1   Focus           336 non-null    str
 2   Agent           336 non-null    int64
 3   Goal_Type       336 non-null    str
 4   Item            336 non-null    str
 5   Item_string     336 non-null    str
 6   Item_len        336 non-null    int64
 7   Response_tag    325 non-null    str
 8   Response        325 non-null    str
 9   Response_Full   336 non-null    str
dtypes: int64(2), str(8)
memory usage: 26.4 KB

In [100]:
responses.head()

,Participant_ID,Focus,Agent,Goal_Type,Item,Item_string,Item_len,Response_tag,Response,Response_Full
0,EXP1_01,I,1,no_goal,Item1,"""If I had heard the rainstorm, I would have fe...",11,L1_transfer_3,L1_transfer,L1_transfer
1,EXP1_01,I,1,no_goal,Item2,"""If I had climbed the mountain cliff, I would ...",12,L1_transfer_3,L1_transfer,L1_transfer
2,EXP1_01,I,1,goal_non_frequent,Item1,"""If I had created an online platform, I would ...",14,L1_transfer_3,L1_transfer,L1_transfer
3,EXP1_01,I,1,goal_non_frequent,Item2,"""If I had invested in technology, I would have...",13,correct_3,correct,correct
4,EXP1_01,I,1,goal_frequent,Item1,"""If I had saved money, I would have gone on ho...",11,correct_3,correct,correct

Metadata dataset:

Clean leading and trailing whitespaces from columns

In [101]:
metadata.columns = metadata.columns.str.strip()

Eliminate "Agent" column -included in responses

In [102]:
metadata = metadata.drop(columns = ["Agent"])

Add know_level and per_level labels

In [103]:
level_mapping = {
    1: "A1",
    2: "A2.1",
    3: "A2.2",
    4: "B1.1",
    5: "B1.2",
    6: "B2.1",
    7: "B2.2",
    8: "C1",
    9: "C2"
}

metadata["Kno_Level_Label"] = metadata["Kno_Level"].map(level_mapping)
metadata["Per_Level_Label"] = metadata["Per_Level"].map(level_mapping)

In [104]:
level_order = [
    "A1",
    "A2.1",
    "A2.2",
    "B1.1",
    "B1.2",
    "B2.1",
    "B2.2",
    "C1",
    "C2"
]

metadata["Kno_Level_Label"] = pd.Categorical(
    metadata["Kno_Level_Label"],
    categories=level_order,
    ordered=True
)

metadata["Per_Level_Label"] = pd.Categorical(
    metadata["Per_Level_Label"],
    categories=level_order,
    ordered=True
)

Add prof_use and prof_need labels

In [105]:
prof_mapping = {
    0: "No",
    1: "Yes"
}

metadata["Prof_Need_Label"] = (
    metadata["Prof_Need"]
    .map(prof_mapping)
)

metadata["Prof_Use_Label"] = (
    metadata["Prof_Use"]
    .map(prof_mapping)
)

Metadata dataset validation

In [106]:
metadata.shape

(56, 22)

In [107]:
metadata.columns

Index(['EXP', 'n', 'Participant_ID', 'Age', 'Gender', 'Kno_Level', 'Per_Level',
       'Bilingual', 'Bi_Parents', 'Multi_Kno', 'Multi_Spk', 'Immersion',
       'Prof_Need', 'Prof_Use', 'Motivation', 'Distractor', 'GN_Score',
       'Difficulty', 'Kno_Level_Label', 'Per_Level_Label', 'Prof_Need_Label',
       'Prof_Use_Label'],
      dtype='str')

In [108]:
metadata.info()

<class 'pandas.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   EXP              56 non-null     int64
 1   n                56 non-null     int64
 2   Participant_ID   56 non-null     str
 3   Age              56 non-null     int64
 4   Gender           56 non-null     int64
 5   Kno_Level        56 non-null     int64
 6   Per_Level        56 non-null     int64
 7   Bilingual        56 non-null     int64
 8   Bi_Parents       56 non-null     int64
 9   Multi_Kno        56 non-null     int64
 10  Multi_Spk        56 non-null     int64
 11  Immersion        56 non-null     int64
 12  Prof_Need        56 non-null     int64
 13  Prof_Use         56 non-null     int64
 14  Motivation       56 non-null     int64
 15  Distractor       56 non-null     int64
 16  GN_Score         56 non-null     int64
 17  Difficulty       56 non-null     int64
 18  Kno_Level_Label  56 non-null     category
 19  Per_Level_Label  56 non-null     category
 20  Prof_Need_Label  56 non-null     str
 21  Prof_Use_Label   56 non-null     str
dtypes: category(2), int64(17), str(3)
memory usage: 9.7 KB

In [109]:
metadata.head()

,EXP,n,Participant_ID,Age,Gender,Kno_Level,Per_Level,Bilingual,Bi_Parents,Multi_Kno,...,Prof_Need,Prof_Use,Motivation,Distractor,GN_Score,Difficulty,Kno_Level_Label,Per_Level_Label,Prof_Need_Label,Prof_Use_Label
0,1,1,EXP1_01,25,0,6,7,0,1,0,...,1,1,4,4,23,3,B2.1,B2.2,Yes,Yes
1,1,2,EXP1_02,38,0,6,7,0,0,1,...,0,0,2,6,27,8,B2.1,B2.2,No,No
2,1,3,EXP1_03,27,1,4,5,0,1,1,...,1,1,6,4,28,7,B1.1,B1.2,Yes,Yes
3,1,4,EXP1_04,53,0,7,9,0,0,1,...,1,1,5,5,39,1,B2.2,C2,Yes,Yes
4,1,5,EXP1_05,53,1,7,8,0,0,1,...,1,1,4,6,35,1,B2.2,C1,Yes,Yes

Merge datasets

In [110]:
merged_data = responses.merge(
    metadata,
    on= "Participant_ID",
    how="left"
)

merged_data validation

In [111]:
merged_data.shape

(336, 31)

In [112]:
merged_data.isnull().sum()

Participant_ID      0
Focus               0
Agent               0
Goal_Type           0
Item                0
Item_string         0
Item_len            0
Response_tag       11
Response           11
Response_Full       0
EXP                 0
n                   0
Age                 0
Gender              0
Kno_Level           0
Per_Level           0
Bilingual           0
Bi_Parents          0
Multi_Kno           0
Multi_Spk           0
Immersion           0
Prof_Need           0
Prof_Use            0
Motivation          0
Distractor          0
GN_Score            0
Difficulty          0
Kno_Level_Label     0
Per_Level_Label     0
Prof_Need_Label     0
Prof_Use_Label      0
dtype: int64

In [113]:
merged_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 336 entries, 0 to 335
Data columns (total 31 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Participant_ID   336 non-null    str
 1   Focus            336 non-null    str
 2   Agent            336 non-null    int64
 3   Goal_Type        336 non-null    str
 4   Item             336 non-null    str
 5   Item_string      336 non-null    str
 6   Item_len         336 non-null    int64
 7   Response_tag     325 non-null    str
 8   Response         325 non-null    str
 9   Response_Full    336 non-null    str
 10  EXP              336 non-null    int64
 11  n                336 non-null    int64
 12  Age              336 non-null    int64
 13  Gender           336 non-null    int64
 14  Kno_Level        336 non-null    int64
 15  Per_Level        336 non-null    int64
 16  Bilingual        336 non-null    int64
 17  Bi_Parents       336 non-null    int64
 18  Multi_Kno        336 non-null    int64
 19  Multi_Spk        336 non-null    int64
 20  Immersion        336 non-null    int64
 21  Prof_Need        336 non-null    int64
 22  Prof_Use         336 non-null    int64
 23  Motivation       336 non-null    int64
 24  Distractor       336 non-null    int64
 25  GN_Score         336 non-null    int64
 26  Difficulty       336 non-null    int64
 27  Kno_Level_Label  336 non-null    category
 28  Per_Level_Label  336 non-null    category
 29  Prof_Need_Label  336 non-null    str
 30  Prof_Use_Label   336 non-null    str
dtypes: category(2), int64(19), str(10)
memory usage: 77.6 KB

In [114]:
merged_data.head()

,Participant_ID,Focus,Agent,Goal_Type,Item,Item_string,Item_len,Response_tag,Response,Response_Full,...,Prof_Need,Prof_Use,Motivation,Distractor,GN_Score,Difficulty,Kno_Level_Label,Per_Level_Label,Prof_Need_Label,Prof_Use_Label
0,EXP1_01,I,1,no_goal,Item1,"""If I had heard the rainstorm, I would have fe...",11,L1_transfer_3,L1_transfer,L1_transfer,...,1,1,4,4,23,3,B2.1,B2.2,Yes,Yes
1,EXP1_01,I,1,no_goal,Item2,"""If I had climbed the mountain cliff, I would ...",12,L1_transfer_3,L1_transfer,L1_transfer,...,1,1,4,4,23,3,B2.1,B2.2,Yes,Yes
2,EXP1_01,I,1,goal_non_frequent,Item1,"""If I had created an online platform, I would ...",14,L1_transfer_3,L1_transfer,L1_transfer,...,1,1,4,4,23,3,B2.1,B2.2,Yes,Yes
3,EXP1_01,I,1,goal_non_frequent,Item2,"""If I had invested in technology, I would have...",13,correct_3,correct,correct,...,1,1,4,4,23,3,B2.1,B2.2,Yes,Yes
4,EXP1_01,I,1,goal_frequent,Item1,"""If I had saved money, I would have gone on ho...",11,correct_3,correct,correct,...,1,1,4,4,23,3,B2.1,B2.2,Yes,Yes

In [115]:
merged_data["Response_Full"].value_counts()

Response_Full
L1_transfer    149
correct        104
L2_other        72
null            11
Name: count, dtype: int64

save data as csv

In [116]:
merged_data.to_csv(
    "../../data/processed/merged_clean.csv",
    index=False
    )